#cloud-config
users:
  - default
  - name: chillbot
    sudo: False

packages:
  - unzip
  - dotnet6

# Configure 1/3 of the temporary (ephemeral) disk as swap
# See https://wiki.ubuntu.com/AzureSwapPartitions for explaination
disk_setup:
  ephemeral0:
    table_type: mbr
    layout: [66, [33, 82]]
    overwrite: True
fs_setup:
  - device: ephemeral0.1
    filesystem: ext4
  - device: ephemeral0.2
    filesystem: swap
mounts:
    - ["ephemeral0.1", "/mnt"]
    - ["ephemeral0.2", "none", "swap", "sw", "0", "0"]

write_files:
  - path: /home/chillbot/sourceDownloadUrl
    permissions: '0644'
    content: |
      <SOURCE_ZIP>

  - path: /home/chillbot/sourceSubDirectory
    permissions: '0644'
    content: |
      <SOURCE_SUB_DIRECTORY>

  - path: /home/chillbot/startChillbot.sh
    permissions: '0744'
    content: |
      source_download_url=$(head -n 1 /home/chillbot/sourceDownloadUrl)
      source_sub_directory=$(head -n 1 /home/chillbot/sourceSubDirectory)

      rm -rf /home/chillbot/source.zip
      rm -rf /home/chillbot/source/*
      wget $source_download_url -O /home/chillbot/source.zip
      unzip /home/chillbot/source.zip -d /home/chillbot/source/
      az login --identity --allow-no-subscriptions
      export DOTNET_CLI_HOME=/home/chillbot
      export CHILLBOT_GuildRepository__Type=AzureBlob
      export CHILLBOT_GuildRepository__AzureBlob__Container=guilds
      export CHILLBOT_GuildRepository__AzureBlob__ConnectionString=$(az keyvault secret show --vault-name <KEY_VAULT_NAME> --name <BLOB_CONNECTION_SECRET_NAME> --query value --out tsv)
      export CHILLBOT_DiscordToken=$(az keyvault secret show --vault-name <KEY_VAULT_NAME> --name <DISCORD_TOKEN_SECRET_NAME> --query value --out tsv)
      export CHILLBOT_ApplicationInsights__InstrumentationKey=$(az keyvault secret show --vault-name <KEY_VAULT_NAME> --name <APPLICATION_INSIGHTS_KEY_SECRET_NAME> --query value --out tsv)
      cd /home/chillbot/source/$source_sub_directory
      dotnet run --configuration Release

runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - chown -R chillbot:chillbot /home/chillbot
  - cd /home/chillbot
  - sudo -H -u chillbot nohup ./startChillbot.sh &

bootcmd:
  - cd /home/chillbot
  - sudo -H -u chillbot test -f ./startChillbot.sh && sudo -H -u chillbot nohup ./startChillbot.sh &
